# Generated by Django 4.2.1 on 2023-05-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_purchaseorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total_order_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
