# Generated by Django 4.2.1 on 2023-05-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poduct_image',
            field=models.ImageField(default='product.jpg', upload_to='product_images'),
        ),
    ]
