# Generated by Django 4.2.1 on 2023-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_product_quantity_alter_sale_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quatity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
