# Generated by Django 4.2.1 on 2023-06-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_product_max_quantity_product_min_quatity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_quatity',
            new_name='min_quantity',
        ),
    ]
