# Generated by Django 4.2.1 on 2023-05-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
