# Generated by Django 4.2.1 on 2023-05-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='poduct_image',
        ),
    ]
